{
  repository(owner: "aiden2480", name: "kanjithing") {
    main: defaultBranchRef {
      target {
        ... on Commit {
          history {
            nodes {
              oid
              pushedDate
              headline: messageHeadline
              url: commitUrl
              committedDate

              file(path: "manifest.json") {
                object {
                  ... on Blob {
                    text
                  }
                }
              }
            }
          }
        }
      }
    }

    releases(last: 10) {
      edges {
        node {
          tagName
        }
      }
    }
  }
}
