name: Publish to chrome webstore

on:
  push:
    paths:
      - manifest.json
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Publish to chrome webstore

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests packaging
      
      - name: Run uploader file
        run: python .github/workflows/webstore.py
        env:
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
